# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c71d8066fd873dfafb10a06b22b8ca0"
name = "Essential-Trust-badges-icons"
handle = "essential-trust-badges-icons"
application_url = "https://indicator-carey-hybrid-emma.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "zehntech-store1.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://indicator-carey-hybrid-emma.trycloudflare.com/auth/callback",
  "https://indicator-carey-hybrid-emma.trycloudflare.com/auth/shopify/callback",
  "https://indicator-carey-hybrid-emma.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
